// Color.kt
package com.martinszuc.templateapp.ui.theme

/**
 * Project: database application
 *
 * Author: Bc. Martin Szuc (matoszuc@gmail.com)
 * GitHub: https://github.com/martinszuc
 *
 *
 * License:
 * This code is licensed under MIT License. You may not use this file except
 * in compliance with the License.
 */

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF984800)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFF821C)
val onPrimaryContainerLight = Color(0xFF2E1100)
val secondaryLight = Color(0xFF8A5028)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFBD94)
val onSecondaryContainerLight = Color(0xFF5D2C06)
val tertiaryLight = Color(0xFF794200)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAD6200)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF241912)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF241912)
val surfaceVariantLight = Color(0xFFFCDCCB)
val onSurfaceVariantLight = Color(0xFF574236)
val outlineLight = Color(0xFF8B7264)
val outlineVariantLight = Color(0xFFDFC1B0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3B2E26)
val inverseOnSurfaceLight = Color(0xFFFFEDE5)
val inversePrimaryLight = Color(0xFFFFB689)
val surfaceDimLight = Color(0xFFECD6CA)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1EA)
val surfaceContainerLight = Color(0xFFFFEADF)
val surfaceContainerHighLight = Color(0xFFFAE4D8)
val surfaceContainerHighestLight = Color(0xFFF4DED3)

val primaryLightMediumContrast = Color(0xFF6D3200)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFBA5900)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF68350F)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFFA4653C)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF663700)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFAD6200)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F5)
val onBackgroundLightMediumContrast = Color(0xFF241912)
val surfaceLightMediumContrast = Color(0xFFFFF8F5)
val onSurfaceLightMediumContrast = Color(0xFF241912)
val surfaceVariantLightMediumContrast = Color(0xFFFCDCCB)
val onSurfaceVariantLightMediumContrast = Color(0xFF533E32)
val outlineLightMediumContrast = Color(0xFF715A4D)
val outlineVariantLightMediumContrast = Color(0xFF8F7667)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF3B2E26)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE5)
val inversePrimaryLightMediumContrast = Color(0xFFFFB689)
val surfaceDimLightMediumContrast = Color(0xFFECD6CA)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F5)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1EA)
val surfaceContainerLightMediumContrast = Color(0xFFFFEADF)
val surfaceContainerHighLightMediumContrast = Color(0xFFFAE4D8)
val surfaceContainerHighestLightMediumContrast = Color(0xFFF4DED3)

val primaryLightHighContrast = Color(0xFF3C1800)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF6D3200)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF3C1800)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF68350F)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF371B00)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF663700)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F5)
val onBackgroundLightHighContrast = Color(0xFF241912)
val surfaceLightHighContrast = Color(0xFFFFF8F5)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFFCDCCB)
val onSurfaceVariantLightHighContrast = Color(0xFF312015)
val outlineLightHighContrast = Color(0xFF533E32)
val outlineVariantLightHighContrast = Color(0xFF533E32)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF3B2E26)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFE7DB)
val surfaceDimLightHighContrast = Color(0xFFECD6CA)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F5)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFF1EA)
val surfaceContainerLightHighContrast = Color(0xFFFFEADF)
val surfaceContainerHighLightHighContrast = Color(0xFFFAE4D8)
val surfaceContainerHighestLightHighContrast = Color(0xFFF4DED3)

val primaryDark = Color(0xFFFFB689)
val onPrimaryDark = Color(0xFF512300)
val primaryContainerDark = Color(0xFFE77100)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFFFB689)
val onSecondaryDark = Color(0xFF512300)
val secondaryContainerDark = Color(0xFF64320C)
val onSecondaryContainerDark = Color(0xFFFFC9AA)
val tertiaryDark = Color(0xFFFFB877)
val onTertiaryDark = Color(0xFF4B2700)
val tertiaryContainerDark = Color(0xFFAB6000)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1C110B)
val onBackgroundDark = Color(0xFFF4DED3)
val surfaceDark = Color(0xFF1C110B)
val onSurfaceDark = Color(0xFFF4DED3)
val surfaceVariantDark = Color(0xFF574236)
val onSurfaceVariantDark = Color(0xFFDFC1B0)
val outlineDark = Color(0xFFA68B7C)
val outlineVariantDark = Color(0xFF574236)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF4DED3)
val inverseOnSurfaceDark = Color(0xFF3B2E26)
val inversePrimaryDark = Color(0xFF984800)
val surfaceDimDark = Color(0xFF1C110B)
val surfaceBrightDark = Color(0xFF44362E)
val surfaceContainerLowestDark = Color(0xFF160C06)
val surfaceContainerLowDark = Color(0xFF241912)
val surfaceContainerDark = Color(0xFF291D16)
val surfaceContainerHighDark = Color(0xFF342720)
val surfaceContainerHighestDark = Color(0xFF3F322A)

val primaryDarkMediumContrast = Color(0xFFFFBC93)
val onPrimaryDarkMediumContrast = Color(0xFF290F00)
val primaryContainerDarkMediumContrast = Color(0xFFE77100)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFBC93)
val onSecondaryDarkMediumContrast = Color(0xFF290F00)
val secondaryContainerDarkMediumContrast = Color(0xFFC58154)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFBD83)
val onTertiaryDarkMediumContrast = Color(0xFF261100)
val tertiaryContainerDarkMediumContrast = Color(0xFFD17C1D)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF1C110B)
val onBackgroundDarkMediumContrast = Color(0xFFF4DED3)
val surfaceDarkMediumContrast = Color(0xFF1C110B)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF8)
val surfaceVariantDarkMediumContrast = Color(0xFF574236)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE3C5B4)
val outlineDarkMediumContrast = Color(0xFFB99D8E)
val outlineVariantDarkMediumContrast = Color(0xFF987E6F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF4DED3)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF342720)
val inversePrimaryDarkMediumContrast = Color(0xFF753600)
val surfaceDimDarkMediumContrast = Color(0xFF1C110B)
val surfaceBrightDarkMediumContrast = Color(0xFF44362E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF160C06)
val surfaceContainerLowDarkMediumContrast = Color(0xFF241912)
val surfaceContainerDarkMediumContrast = Color(0xFF291D16)
val surfaceContainerHighDarkMediumContrast = Color(0xFF342720)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3F322A)

val primaryDarkHighContrast = Color(0xFFFFFAF8)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFBC93)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFAF8)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFFBC93)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFAF8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFBD83)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF1C110B)
val onBackgroundDarkHighContrast = Color(0xFFF4DED3)
val surfaceDarkHighContrast = Color(0xFF1C110B)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF574236)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF8)
val outlineDarkHighContrast = Color(0xFFE3C5B4)
val outlineVariantDarkHighContrast = Color(0xFFE3C5B4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFF4DED3)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF481E00)
val surfaceDimDarkHighContrast = Color(0xFF1C110B)
val surfaceBrightDarkHighContrast = Color(0xFF44362E)
val surfaceContainerLowestDarkHighContrast = Color(0xFF160C06)
val surfaceContainerLowDarkHighContrast = Color(0xFF241912)
val surfaceContainerDarkHighContrast = Color(0xFF291D16)
val surfaceContainerHighDarkHighContrast = Color(0xFF342720)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3F322A)




